=== AlexeyMikhailovsky/jwd_task3/target/classes/flowers.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">


    <element name="plant" type="tns:Plant" abstract="true"/>
    <element name="tree" type="tns:Tree" substitutionGroup="tns:plant"/>
    <element name="flower" type="tns:Flower" substitutionGroup="tns:plant"/>

    <element name="plants">
        <complexType>
            <sequence>
                <element ref="tns:plant" maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
    </element>

  <complexType name="Plant">
      <sequence>
          <element name="name" type="string"></element>
          <element name="soil" type="tns:Soil"></element>
          <element name="visual-parameters" type="tns:VisualParameters"></element>
          <element name="growing-tips" type="tns:GrowingTips"></element>
          <element name="multiplying" type="tns:Multiplying"></element>
      </sequence>
      <attribute name="origin" type="tns:Origin" use="required"></attribute>
      <attribute name="id" type="tns:PlantId" use="required"/>
  </complexType>

  <complexType name="VisualParameters">
      <sequence>
          <element name="stem-color" type="tns:Color" default="green"/>
          <element name="leaf-color" type="tns:Color" default="green"/>
          <element name="average-size" type="tns:Size"/>
      </sequence>
  </complexType>
    
   <complexType name="GrowingTips">
       <sequence>
           <element name="temperature" type="tns:Temperature"/>
           <element name="lighting" type="tns:Lighting"/>
           <element name="watering" type="tns:Watering"/>
       </sequence>
   </complexType>

    <simpleType name="Color">
        <restriction base="string">
            <enumeration value="colorless"/>
            <enumeration value="red"/>
            <enumeration value="orange"/>
            <enumeration value="yellow"/>
            <enumeration value="green"/>
            <enumeration value="blue"/>
            <enumeration value="navy"/>
            <enumeration value="purple"/>
            <enumeration value="pink"/>
            <enumeration value="white"/>
            <enumeration value="brown"/>
        </restriction>
    </simpleType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="leaves"/>
            <enumeration value="cuttings"/>
            <enumeration value="seeds"/>
        </restriction>
    </simpleType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="podzolic"/>
            <enumeration value="sod-podzolic"/>
            <enumeration value="unpaved"/>
        </restriction>
    </simpleType>
    
    <simpleType name="Watering">
        <restriction base="string">
            <pattern value="(\d+).?(\d*)\s*(ml\/w)"/>
        </restriction>
    </simpleType>
    
    <simpleType name="PlantId">
        <restriction base="ID">
            <pattern value="plant-\d{1,10}"/>
        </restriction>
    </simpleType>

    <simpleType name="Lighting">
        <restriction base="string">
            <enumeration value="photophilous"/>
            <enumeration value="not-photophilous"/>
        </restriction>
    </simpleType>
    
    <simpleType name="Temperature">
        <restriction base="string">
            <pattern value="[\d]*[,.]?[\d]* [CFK]"/>
        </restriction>
    </simpleType>

    <simpleType name="Origin">
        <restriction base="string">
            <pattern value="[a-zA-Z]{2,}"/>
        </restriction>
    </simpleType>

    <simpleType name="Size">
        <restriction base="string">
            <pattern value="(\d+).?(\d*)\s*(m|cm)"/>
        </restriction>
    </simpleType>

    <complexType name="Tree">
        <complexContent>
            <extension base="tns:Plant">
                <attribute name="crown-width" type="tns:Size" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Flower">
        <complexContent>
            <extension base="tns:Plant">
                <attribute name="petal-number" type="int" use="required"/>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== AlexeyMikhailovsky/jwd_task3/resources/flowers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/flowers"
        xsi:schemaLocation="http://www.example.com/flowers flowers.xsd">

    <flower id="plant-1" petal-number="6" origin="USA">
        <name>Primrose</name>
        <soil>podzolic</soil>
        <visual-parameters>
            <stem-color>green</stem-color>
            <leaf-color>green</leaf-color>
            <average-size>15 cm</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25 C</temperature>
            <lighting>photophilous</lighting>
            <watering>100 ml/w</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="plant-2" petal-number="6" origin="USA">
        <name>Tawny Daylily</name>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>yellow</stem-color>
            <leaf-color>red</leaf-color>
            <average-size>60 cm</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25 C</temperature>
            <lighting>photophilous</lighting>
            <watering>200 ml/w</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>
    
    <flower origin="Canada" id="plant-3" petal-number="6">
        <name>Shrub Althea</name>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>green</stem-color>
            <leaf-color>pink</leaf-color>
            <average-size>1.2 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25 C</temperature>
            <lighting>photophilous</lighting>
            <watering>120 ml/w</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="plant-4" petal-number="6" origin="Taiwan">
        <name>Hardy Hibiscus</name>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>blue</stem-color>
            <leaf-color>white</leaf-color>
            <average-size>90 cm</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>28 C</temperature>
            <lighting>photophilous</lighting>
            <watering>340 ml/w</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
    </flower>

    <flower id="plant-5" petal-number="8" origin="USA">
        <name>Florida Cranberry</name>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>red</stem-color>
            <leaf-color>white</leaf-color>
            <average-size>1.3 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>26 C</temperature>
            <lighting>photophilous</lighting>
            <watering>300 ml/w</watering>
        </growing-tips>
        <multiplying>leaves</multiplying>
    </flower>

    <flower origin="Brazil" id="plant-6" petal-number="5">
        <name>Venice</name>
        <soil>podzolic</soil>
        <visual-parameters>
            <stem-color>green</stem-color>
            <leaf-color>purple</leaf-color>
            <average-size>60 cm</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>24 C</temperature>
            <lighting>photophilous</lighting>
            <watering>100 ml/w</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
    </flower>

    <flower id="plant-7" petal-number="6" origin="USA">
        <name>Rose of Sharon</name>
        <soil>podzolic</soil>
        <visual-parameters>
            <stem-color>green</stem-color>
            <leaf-color>purple</leaf-color>
            <average-size>2.6 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20 C</temperature>
            <lighting>photophilous</lighting>
            <watering>100 ml/w</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="plant-8" petal-number="5" origin="China">
        <name>Rose Mallow</name>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>green</stem-color>
            <leaf-color>red</leaf-color>
            <average-size>60 cm</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>29 C</temperature>
            <lighting>photophilous</lighting>
            <watering>400 ml/w</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <tree origin="Butan" id="plant-9" crown-width="4 m">
        <name>Acacia</name>
        <soil>unpaved</soil>
        <visual-parameters>
            <stem-color>brown</stem-color>
            <leaf-color>green</leaf-color>
            <average-size>3 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>33.2 C</temperature>
            <lighting>photophilous</lighting>
            <watering>600 ml/w</watering>
        </growing-tips>
        <multiplying>leaves</multiplying>
    </tree>

    <tree origin="Arabic" id="plant-10" crown-width="3 m">
        <name>Albizia</name>
        <soil>unpaved</soil>
        <visual-parameters>
            <stem-color>brown</stem-color>
            <leaf-color>green</leaf-color>
            <average-size>6 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>32.2 C</temperature>
            <lighting>photophilous</lighting>
            <watering>250 ml/w</watering>
        </growing-tips>
        <multiplying>leaves</multiplying>
    </tree>

    <tree origin="Pakistan" id="plant-11" crown-width="2.2 m">
        <name>Almond</name>
        <soil>unpaved</soil>
        <visual-parameters>
            <stem-color>brown</stem-color>
            <leaf-color>white</leaf-color>
            <average-size>2.2 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>22.2 C</temperature>
            <lighting>photophilous</lighting>
            <watering>222 ml/w</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
    </tree>

    <tree origin="Japan" id="plant-12" crown-width="3.5 m">
        <name>Malus floribunda</name>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>brown</stem-color>
            <leaf-color>white</leaf-color>
            <average-size>5 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25.6 C</temperature>
            <lighting>photophilous</lighting>
            <watering>284 ml/w</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </tree>

    <tree origin="Korea" id="plant-13" crown-width="8 m">
        <name>Populus davidiana</name>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>white</stem-color>
            <leaf-color>green</leaf-color>
            <average-size>22 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>28.5 C</temperature>
            <lighting>photophilous</lighting>
            <watering>4200 ml/w</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
    </tree>

    <tree origin="Africa" id="plant-14" crown-width="15 m">
        <name>Baobab</name>
        <soil>unpaved</soil>
        <visual-parameters>
            <stem-color>brown</stem-color>
            <leaf-color>green</leaf-color>
            <average-size>25 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>36.6 C</temperature>
            <lighting>photophilous</lighting>
            <watering>60000 ml/w</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </tree>

    <tree origin="Alp" id="plant-15" crown-width="3.2 m">
        <name>Callistemon pityoides</name>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>yellow</stem-color>
            <leaf-color>red</leaf-color>
            <average-size>2.5 m</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>28.6 C</temperature>
            <lighting>photophilous</lighting>
            <watering>750 ml/w</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </tree>

    <tree origin="Japan" id="plant-16" crown-width="50 cm">
        <name>Bonsai</name>
        <soil>podzolic</soil>
        <visual-parameters>
            <stem-color>brown</stem-color>
            <leaf-color>green</leaf-color>
            <average-size>40 cm</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>27.23 C</temperature>
            <lighting>photophilous</lighting>
            <watering>12.56 ml/w</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
    </tree>

</plants>
